apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
commonLabels:
  app: prometheus
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- service-account.yaml
- cluster-role-binding.yaml
- cluster-role.yaml

configMapGenerator:
- name: prometheus-config
  files:
  - conf/prometheus.yml