global:
  # defines the interval based on which prometheus scrapes a monitored target
  scrape_interval: 10s
  # defines the interval based on which prometheus evaluates the query for alerting
  evaluation_interval: 10s
  rule_files:
    - rules.yml
  alerting:
    alertmanagers:
      - static_configs:
          - targets:
              - localhost: 9093
  scrape_configs:
    - job_name: prometheus
      static_configs:
        - targets:
            - 'localhost:9090'
    - job_name: node_exporter
      static_configs:
        - targets:
            - 'localhost:9100'
